version: '2'
services:

 mongodb:
  container_name: mongodb
  image: mongo
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: example
  ports:
   - "27017:27017"
  entrypoint: mongod --bind_ip_all
#  command: mongod --logpath=/dev/null # --quiet

 backend:
  build: .
  ports:
   - "8080:8080"
  environment:
   SPRING_PROFILES_ACTIVE: uat
   DATABASE: t_db
   MONGODB_HOST: mongodb
   MONGODB_PORT: 27017
   SERVER_PORT: 8080
  links:
   - mongodb
